// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {slack} from '../models';
import {clockin} from '../models';

export function CarregarCredenciais():Promise<main.Credentials>;

export function DefinirStatus(arg1:slack.Status):Promise<void>;

export function DeletarCredenciais():Promise<void>;

export function EnviarMensagem(arg1:string):Promise<void>;

export function ExecutarOperacao(arg1:clockin.TipoOperacao):Promise<void>;

export function LimparStatus():Promise<void>;

export function LoginPonto(arg1:string,arg2:string):Promise<void>;

export function ObterLocalizacaoAtual():Promise<string>;

export function ObterLocalizacoesDisponiveis():Promise<Array<clockin.Localizacao>>;

export function ObterOperacoesDisponiveis():Promise<Array<clockin.TipoOperacao>>;

export function ObterStatusAtual():Promise<slack.Status>;

export function SalvarCredenciais(arg1:main.Credentials):Promise<void>;

export function SelecionarLocalizacao(arg1:clockin.Localizacao):Promise<void>;

export function VerificarCredenciaisSalvas():Promise<void>;

export function VerificarSessaoSlack():Promise<void>;
