// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CarregarCredenciais() {
  return window['go']['main']['App']['CarregarCredenciais']();
}

export function DefinirStatus(arg1) {
  return window['go']['main']['App']['DefinirStatus'](arg1);
}

export function DeletarCredenciais() {
  return window['go']['main']['App']['DeletarCredenciais']();
}

export function EnviarMensagem(arg1) {
  return window['go']['main']['App']['EnviarMensagem'](arg1);
}

export function ExecutarOperacao(arg1) {
  return window['go']['main']['App']['ExecutarOperacao'](arg1);
}

export function InicializarSlack() {
  return window['go']['main']['App']['InicializarSlack']();
}

export function LimparStatus() {
  return window['go']['main']['App']['LimparStatus']();
}

export function LoginPonto(arg1, arg2) {
  return window['go']['main']['App']['LoginPonto'](arg1, arg2);
}

export function ObterLocalizacaoAtual() {
  return window['go']['main']['App']['ObterLocalizacaoAtual']();
}

export function ObterLocalizacoesDisponiveis() {
  return window['go']['main']['App']['ObterLocalizacoesDisponiveis']();
}

export function ObterOperacoesDisponiveis() {
  return window['go']['main']['App']['ObterOperacoesDisponiveis']();
}

export function ObterStatusAtual() {
  return window['go']['main']['App']['ObterStatusAtual']();
}

export function PrepararMensagem(arg1) {
  return window['go']['main']['App']['PrepararMensagem'](arg1);
}

export function SalvarCredenciais(arg1) {
  return window['go']['main']['App']['SalvarCredenciais'](arg1);
}

export function SelecionarLocalizacao(arg1) {
  return window['go']['main']['App']['SelecionarLocalizacao'](arg1);
}

export function VerificarCredenciaisSalvas() {
  return window['go']['main']['App']['VerificarCredenciaisSalvas']();
}

export function VerificarSessaoSlack() {
  return window['go']['main']['App']['VerificarSessaoSlack']();
}
